from enum import Enum

# settings

#WIN_RES = WIDTH, HEIGHT = 1280, 720
WIN_RES = WIDTH, HEIGHT = 1600, 900
# WIN_RES = WIDTH, HEIGHT = 1920, 1080
HALF_WIDTH, HALF_HEIGHT = WIDTH // 2, HEIGHT // 2
FOCAL_LEN = 250
SCALE = 100
SPEED = 0.05
MAP_BOUND = 10.0
AIR_LANE_REFERENCE_HEIGHT = 1.0
PLAYER_MIN_ALTITUDE = 0.1
PLAYER_MAX_ALTITUDE = AIR_LANE_REFERENCE_HEIGHT
PLAYER_HEIGHT_HIT_RADIUS = 0.12
ENEMY_MIN_HEIGHT = 0.35
ENEMY_SPAWN_MAX_HEIGHT = AIR_LANE_REFERENCE_HEIGHT
ENEMY_MATCH_MAX_HEIGHT = 6.0
ENEMY_HEIGHT_MATCH_RADIUS = MAP_BOUND * 1.5
ENEMY_HEIGHT_ADJUST_SPEED = 0.05
ENEMY_HEIGHT_HIT_RADIUS = 0.16
PROJECTILE_HEIGHT_HIT_RADIUS = 0.10
MENU = 'menu' # *States
GAME = 'game'
GAME_OVER = 'game_over'


class WeaponType(str, Enum):
    REVOLVER = "revolver"
    SHOTGUN = "shotgun"
    MINIGUN = "minigun"
